.\" Copyright (c) 2024, oldteam. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright notice, this
.\"    list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright notice,
.\"    this list of conditions and the following disclaimer in the documentation
.\"    and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.TH URL_BUILD 3 "13 June 2024"
.SH NAME
url_build \- creates an url_t* object with the specified fields
.SH SYNOPSIS
.nf
.ft B
#include <ncsnet/url.h>
url_t  *url_build(const char *scheme, const char *paths,
                  const char *host, const char *userinfo,
                  const char *port, const char *querys,
                  int type);

.ft
.fi
.SH DESCRIPTION
.BR url_build ()
forms an
.B url_t*
object and fills its fields with arguments, the following macros
are specified as type,
.IP
.ft B
.nf
/* scheme:/// */
#define URL_INTER_TYPE_SCHEMEPATHSLASH 0

/* scheme:// */
#define URL_INTER_TYPE_DEFAULT         1

/* scheme: */
#define URL_INTER_TYPE_SCHEMEPATH      2
.ft
.fi
.PP
in case of success returns
.B url_t*
object, in case of error returns
.BR NULL .
