.TH NCSRAW 1 "June 2024" "???" "Nesca Raw Manual"
.SH NAME
ncsraw \- интерфейс для работы с низкоуровневыми сетями.
.SH SYNOPSIS
.nf
.ft B
#include "ncsnet/nescanet.h"
.ft
.LP
.ft B
ncsraw_t *ncsraw_init(void);
void      ncsraw_build(ncsraw_t *n, char *errbuf, const char *fmt, ...);
void      ncsraw_option(ncsraw_t *n, int option, const char *val);
ssize_t   ncsraw_send(ncsraw_t *n);
void      ncsraw_free(ncsraw_t *n);
.ft
.fi
.SH DESCRIPTION
.BR ncsraw_init ()
возвращает указатель на ncsraw_t структуру, перед этим выделяя под нее память, и иницилизируя поля, (дескрипторов не открывает).
.PP
.BR ncsraw_build ()
заполняет два поля ncsraw_t (pkt, pktlen) по указаному форматированию в fmt, если произошла ошибка, записывает ее в errbuf; максимальному размеру errbuf соответсвует макрос NCSBUILD_ERRBUF_MAXLEN.
.PP
.BR ncsraw_option ()
устанавливает опцию option на указанный ncsraw_t с указаным значением в val.
.PP
.BR ncsraw_send ()
записывает ncsraw_t->pkt в ncsraw_t->fd, и возвращает количество записанных байт.
.PP
.BR ncsraw_free ()
очищает память выделенную под указанный ncsraw_t.
.SH SEE ALSO
.BR ncsraw_init (1)
.BR ncsraw_build (1)
.BR ncsraw_option (1)
.BR ncsraw_send (1)
